version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
    - "6379:6379"
    networks: [app]

  jacks:
    build:
       context: .
       dockerfile: Dockerfile.JACKS
    depends_on:
    - redis
    ports:
    - "5000:5000"
    networks: [app]
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery worker -b "redis://redis:6379/0" -El debug
    depends_on:
    - redis
    - jacks
    networks: [app]

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery flower -b "redis://redis:6379/0" -El debug --address=0.0.0.0
    depends_on:
    - celery-worker
    ports:
    - "5555:5555"
    networks: [app]

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.1/24
